### ISSUE TITLE
Daily Bluezone IDs trong ngày đầu tiên người dùng cài ứng dụng bị sai

### ISSUE THREAD

**Issue by thaidn** [BluezoneGlobal/react-native-bluetooth-scan#12]
Phiên bản: 2.0.2
Ngày phát hành: 15/05/2020
Hệ điều hành: Android

Đoạn code khởi tạo Bluezone base ID có một lỗi nhỏ khiến cho những daily Bluezone IDs trong ngày đầu tiên người dùng cài ứng dụng bị sai:

https://github.com/BluezoneGlobal/react-native-bluetooth-scan/blob/master/lib/android/src/main/java/com/scan/bluezoneid/BluezoneIdGenerator.java#L90-L104

Hàm `initRandomBluezoneBaseId()` được gọi hai lần, một ở dòng 94 và một ở dòng 96. Kết quả ở dòng 94 được dùng để tạo ra ID của ngày đầu tiên, còn dòng 96 được ghi xuống database.

**Comment by thaidn** [comment]
(hit enter too early)

Tôi cũng đã kiểm tra thông qua reverse engineering và thấy lỗi này xuất hiện trong phiên bản Bluezone mới nhất trên Google Play Store.

Lỗi này sẽ khiến dữ liệu báo cáo bị sai, dẫn đến việc truy vết không chính xác, nhưng chỉ trong ngày đầu tiên, bắt đầu từ ngày thứ hai dữ liệu sẽ đúng. Đây không phải là lỗ hổng bảo mật, mà chỉ là lỗi lập trình thông thường.

**Comment by thaidn** [comment]
Có vẻ như lỗi này đã được sửa trong phiên bản 2.0.3 ra ngày hôm nay. Nhờ các bạn trong team phát triển xác nhận và đóng report này lại nếu đúng.

**Comment by BkavMS17** [comment]
Cảm ơn ThaiDN đã góp ý, lỗi này Team đã phát hiện và đã sửa trong bản 2.0.3.
