### ISSUE TITLE
Bluezone IDs should be rotated

### ISSUE THREAD

**Issue by thaidn** [BluezoneGlobal/react-native-bluetooth-scan#4]
I'm writing in English because I thought it would be useful for non-Vietnamese-speaking people to voice their opinions.

I reported this vulnerability over email on April 23, but I haven't got a response, so I thought I'd report it again here. If there's already a plan to address it, please share what you're going to do.

Bluezone assigns each installation a fixed 6-character ID, and broadcasts it over and over again. There are many contact tracing designs, but I think Bluezone is the only one using a fixed ID. I hope we all understand why using a fixed ID is bad for user privacy, but please let me know if you want me to explain further.

Some people think that changing the ID doesn't matter because the Bluetooth MAC address is fixed anyway. This is not true.

Bluetooth has two sub standards: Bluetooth Classic and Bluetooth Low Energy. A Bluetooth Classic device can be either discoverable or non-discoverable. When it is discoverable, it broadcasts its MAC address, device name and other information. But when it is non-discoverable, it doesn't broadcast anything. For privacy, neither Android nor iOS is discoverable by default. In general phones are discoverable if and only if the Bluetooth pairing screen (see my next comment) is running in the foreground, e.g., only when the user is wanting to pair with other devices.

Both Android and iOS also randomize the MAC address when broadcasting BLE advertisements. On Android, experiments by various groups show that restarting BLE advertising causes the OS to choose a new random MAC address, at least on Samsung and Pixel phones. On iOS, experiments by a friend of mine show that the OS automatically chooses a new random MAC address every hour or so.

To fix this issue, I recommend generating ephemeral IDs, following the design of one of these projects:
* [DP3T](https://github.com/DP-3T/documents/blob/master/DP3T%20White%20Paper.pdf)
* [TCN](https://github.com/TCNCoalition/TCN)
* Apple/Google's proposal is also a good one -- the current public spec has a few issues, but it'll be updated soon. A small advantage of this design is that you can seamlessly switch to the new Android/iOS APIs when they're released in a couple of weeks.

Please confirm that you agree that this is a vulnerability and you're going to fix it. I can help review your implementation.

I've asked professor Kenny Paterson @kennypaterson from DP3T and Henry de Valence @hdevalence from TCN  for help. They're 'CCed, will receive notifications, can help guide you integrate with their design and implementation. Please feel free to ask any questions that you may have about DP3T or TCN. You can ask in Vietnamese if you don't feel comfortable with English. I'll translate.

Edit: change "Bluetooth System Setting app" to "Bluetooth pairing screen".
Edit: note that Kenny and Henry are 'CCed and can answer questions.
Edit: clarify that BLE experiments were done on Samsung and Pixel phones.

**Comment by thaidn** [comment]
I want to clarify when phones are discoverable when Bluetooth is turned on.

* Android phones (tested on Pixel, see my next comment) are discoverable in the following scenarios:
  * The user is seeing this screen
![Android Bluetooth Setting screen](https://img.gadgethacks.com/img/78/25/63574996642886/0/android-basics-connect-bluetooth-device.w1456.jpg)

  * An app enables discoverability using [this API](https://developer.android.com/guide/topics/connectivity/bluetooth#EnableDiscoverability). A dialog will be displayed, requesting the user's permission to make the device discoverable:
![the enabling discoverability dialog](https://developer.android.com/images/bt_enable_discoverable.png)

* iPhones are only discoverable in the following scenarios:
  * The user is seeing this screen
  ![Iphone Bluetooth Setting screen](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iOS/ios12-iphonex-settings-bluetooth-devices.jpg)

  * I don't know if iOS provides an API that allows apps to enable discoverability like Android.

Edit: clarify that the first claim was only tested on Pixel.

**Comment by thaidn** [comment]
It's been brought to my attention that on Android phones from Chinese manufacturers such as Xiaomi, Oneplus, Oppo Bluetooth will always be discoverable when enabled, and users can't change this setting.

For years users have [widely](https://xiaomi.eu/community/threads/switch-for-bluetooth-visibility-discoverability.53527/) [complained](https://www.reddit.com/r/Xiaomi/comments/7c5mhx/apparently_in_miui_9_bluetooth_is_always/) about this terrible security/privacy loophole to no avail.

It looks like contact tracing apps like Bluezone should check and turn discoverability off, of course with user permission. This seems possible, as advertised by this app: https://play.google.com/store/apps/details?id=com.minol.miuibluetoothfix.

More work is needed to verify whether these devices randomize the Bluetooth LE MAC address. If not, what countermeasures are possible.

@kennypaterson @hdevalence This is relevant to TCN and DP3T in its own right.

**Comment by thaidn** [comment]
>More work is needed to verify whether these devices randomize the Bluetooth LE MAC address. If not, what countermeasures are possible.

Cl0v3r -- he was the person that brought up the discoverability issue in Android phones made by Xiaomi, Oneplus, Oppo -- told me that he did some testing and found that it's likely that Xiaomi Mi 9 randomizes the Bluetooth LE MAC address every 10 minutes.

**Comment by BkavMS17** [comment]
Chào @thaidn , cảm ơn bạn đã có góp ý cho dự án Bluezone. Vì bạn là người Việt Nam nên mình sẽ trao đổi bằng tiếng Việt trong phần trả lời của mình.

> Some people think that changing the ID doesn't matter because the Bluetooth MAC address is fixed anyway. This is not true.

Trong whitepaper nhóm phát triển cũng nói rõ:

>  Với tín hiệu Bluetooth Classic quảng bá sẽ luôn gắn với 1 địa chỉ MAC cố định của điện thoại từ khi xuất xưởng

Nói về an ninh mạng thì khi đã quảng bá một thông tin cố định như vậy là có thể định danh thiết bị rồi, hacker sẽ dùng cách này hay cách khác để có nếu muốn, do đó việc sinh ID ngẫu nhiên không làm thiết bị ẩn danh tốt hơn. Trong whitepaper, nhóm cũng không nói là không có ý định sinh ID ngẫu nhiên, trái lại Bluezone sẽ sử dụng ID ngẫu nhiên khi nó có ý nghĩa. Cụ thể trong whitepaper đã nói rằng nhóm có những trao đổi với nhóm của Apple và Google về vấn đề của Bluetooth Classic, hi vọng dự án hợp tác giữa Apple và Google có thể sớm đưa ra chuẩn Bluetooth mới. Khi đó Bluezone sẽ sử dụng phần sinh ID ngẫu nhiên của Apple/Goolge vì lúc đó ID ngẫu nhiên mới có ý nghĩa. Hiện tại nhóm vẫn đang tích cực làm việc cùng với đội phát triển API của Apple và GG để thúc đẩy việc sử dụng ID ngẫu nhiên hiệu quả và có ý nghĩa hơn.

Cảm ơn @thaidn và mong tiếp tục nhận được đóng góp của bạn với dự án này.

**Comment by thaidn** [comment]
>Nói về an ninh mạng thì khi đã quảng bá một thông tin cố định như vậy là có thể định danh thiết bị rồi, hacker sẽ dùng cách này hay cách khác để có nếu muốn, do đó việc sinh ID ngẫu nhiên không làm thiết bị ẩn danh tốt hơn.

Tôi đã giải thích tại sao điện thoại sẽ không quảng bá địa chỉ của Bluetooth Classic. Điện thoại của một số nhà sản xuất Trung Quốc làm vậy, nhưng điện thoại của Samsung hay Google thì không. Vả lại app cũng có thể tắt chức năng quảng bá này trên điện thoại của Trung Quốc.

>Trong whitepaper, nhóm cũng không nói là không có ý định sinh ID ngẫu nhiên, trái lại Bluezone sẽ sử dụng ID ngẫu nhiên khi nó có ý nghĩa. Cụ thể trong whitepaper đã nói rằng nhóm có những trao đổi với nhóm của Apple và Google về vấn đề của Bluetooth Classic, hi vọng dự án hợp tác giữa Apple và Google có thể sớm đưa ra chuẩn Bluetooth mới. Khi đó Bluezone sẽ sử dụng phần sinh ID ngẫu nhiên của Apple/Goolge vì lúc đó ID ngẫu nhiên mới có ý nghĩa. Hiện tại nhóm vẫn đang tích cực làm việc cùng với đội phát triển API của Apple và GG để thúc đẩy việc sử dụng ID ngẫu nhiên hiệu quả và có ý nghĩa hơn.

Nếu Bluezone chuyển sang sử dụng API của Apple/Google thì quá tốt.

Nhưng nói cho rõ phần Apple và Google làm không liên quan gì đến việc thay đổi địa chỉ Bluetooth Classic. Giải pháp này sử dụng Bluetooth Low Energy. Địa chỉ BLE đã được chọn ngẫu nhiên rồi, giải pháp của Apple và Google chỉ đồng bộ việc thay đổi địa chỉ BLE và mã định dang người dùng.

**Comment by hadv** [comment]
Trong tài liệu, Bluezone còn muốn thu thập địa chỉ MAC của những người không sử dụng Bluezone App nữa mà nên họ không quan tâm đến việc sử dụng địa chỉ MAC ngẫu nhiên để đảm bảo privacy cho người dùng đâu ;) 

![image](https://user-images.githubusercontent.com/941411/80898481-121b1c00-8d2e-11ea-992b-849563a902cb.png)

![image](https://user-images.githubusercontent.com/941411/80898515-80f87500-8d2e-11ea-8df8-9ec013a05022.png)

**Comment by thenewvu** [comment]
@thaidn said what he found, that's a good thing, but he didn't say the other facts, so many people stand on his side, I won't disagree with anyone, I just want to tell you just a little more facts.

* The fact is your phone actively exposes your data to **a lot of other things**, in **much larger range** than bluetooth, such as GPS, cell towers, wireless hotspot, ...
* The fact is the exposed data can be your IP, SIM identity, device MAC, device name, SMS, call audio, internet browsing data...
* The fact is the exposed data can be captured by a middle device.
* The fact is the exposed data can be shared/leaked to 3rd parties by service vendors.

We all live in a tech industry with a lot of incomplete standards, some even get worse. This issue is a problem, but if you consider it with others, this one is minor.

Let's stand from the view of makers, who actually make things happen, it can take months, to years to build something up that works, it can take even more months to stabilize from a change, specially an architectural change. If you actually built something, you understand what I mean.

This project is one of **fast responses** to the C19 pandemic by a Vietnamese company, though I don't see (doesn't mean it doesn't have) any Vietnamese core techs here, only "using" trending things, but I still consider it as a good **fast response**.

That's it, be safe, everyone.

**Comment by thenewvu** [comment]
For anyone still want to understand more about how a contact tracing app can work usefully and safely, I've found an article that pretty easy to understand (written in quite plain English), reasonable both in tech and in fact:

[The security behind the NHS contact tracing app](https://www.ncsc.gov.uk/blog-post/security-behind-nhs-contact-tracing-app)

Section "Here comes the crypto" describes a way that tracing IDs can be issued and managed, but most important lines for me:

> most importantly provides the insights the public health professionals need to better manage the virus in the UK

> An app that provides fantastic provable privacy but doesn’t help stop the spread of the disease isn’t a useful tool

**Comment by thaidn** [comment]
>Trong whitepaper, nhóm cũng không nói là không có ý định sinh ID ngẫu nhiên, trái lại Bluezone sẽ sử dụng ID ngẫu nhiên khi nó có ý nghĩa. Cụ thể trong whitepaper đã nói rằng nhóm có những trao đổi với nhóm của Apple và Google về vấn đề của Bluetooth Classic, hi vọng dự án hợp tác giữa Apple và Google có thể sớm đưa ra chuẩn Bluetooth mới. Khi đó Bluezone sẽ sử dụng phần sinh ID ngẫu nhiên của Apple/Goolge vì lúc đó ID ngẫu nhiên mới có ý nghĩa. Hiện tại nhóm vẫn đang tích cực làm việc cùng với đội phát triển API của Apple và GG để thúc đẩy việc sử dụng ID ngẫu nhiên hiệu quả và có ý nghĩa hơn.

Hôm nay Google và Apple đã ra mắt giải pháp và cho phép các đối tác thử nghiệm. Tôi hi vọng team Bluezone sẽ sớm đăng ký sử dụng. Để đăng ký, team Bluezone vui lòng liên hệ với team Google/Apple mà trước giờ Bluezone đã nói chuyện.

Nếu team có gặp trục trặc hay thắc mắc gì, tôi rất sẵn lòng hỗ trợ. Email công việc của tôi là thaidn@google.com.

**Comment by thaidn** [comment]
@thenewvu 

From TFA:

>When you download and run the app, your phone is assigned a big random number (a 128 bit GUID) to act as your fixed but anonymous identity (we’ll call it the installation ID from now on). Only your device and the NHS server ever know that. The app asks the user the first part of their postcode (LS1 or SW1A, for example, for NHS resource planning, mainly) and it records the model of your phone (for example ‘Apple iPhone 10,2’). Your phone and the system also end up agreeing a few cryptographic keys, including a key used to authenticate your installation, and some system parameters. Nothing identifying and no personal data are taken from the device or the user.

>Every day, your device generates a random elliptic curve key pair and encrypts your installation ID (and some other administrative stuff like time periods) with it in a way that only the NHS server can recover, giving you a daily, random-looking, encrypted 'blob'. 

This means the NHS app is centralized -- this is bad or good depending on whom you talk to -- but it doesn't use a fixed ID. Bluezone remains the only contact tracing app in the whole world using a fixed ID.

**Comment by thenewvu** [comment]
It uses fixed IDs, but they are encrypted with new key everyday, you quoted it:

> When you download and run the app, your phone is assigned a big random number (a 128 bit GUID) to act as your **fixed** but anonymous identity (we’ll call it the installation ID from now on). Only your device and the NHS server ever know that.

The more important problem of bluezone IDs is it is easy to guess, and has a weak collision resistance. But they may have solved it already by prefixing created time their IDs on backend side (my guess).

**Comment by thaidn** [comment]
@thenewvu that ID is not the ID that it'd broadcast over BLE. The last paragraph shows how it generates the BLE IDs. Bluezone, however, broadcasts the same ID over and over again.

**Comment by thenewvu** [comment]
As I understand, that is the fixed ID, just encrypted, server-side will decrypt to recover the fixed ID.

Back to the problem here, instead ranting about using this better, using that better, we should be constructive, the makers have to deal with scaling, backward compatibility and maintenance problems, we don't.

The question we can help here is, **How to improve their tracing IDs that will not blow up their app and their back-end side, and still able to work with existing IDs?**

A naive solution comes up to my mind is:

```
| 1 byte for version | 8 bytes for expire time | 7 bytes for random |
```

* The version byte is not in `0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz`, because old IDs can contain those bytes.
* The expire time can be ID created time + 14 days. 8 bytes if posix time, 4 bytes if count from 1/1/2020.
* The ID will be regenerated if:
  * The ID didn't contact with any confirmed/possible infected IDs
  * The expire time is passed.

This ID formula has stronger collision resistance. New code can easily detect new IDs by version byte. Old code is still needed to handle old IDs.

**Comment by khanguy00** [comment]
@thenewvu why do you quote a random article here? I don't feel we have anything to do with that. The problem here is that Bluezone ID should be rotated or not. From your last comments, I guess you're agreed that it should, but disagreed about how to generate IDs (am I wrong?). That's fine.

The thing is the development team haven't replied about that. What we expect is that they know and answer properly, then we can go to the next question, such as what is the best of ID generator. It's non sense if we keep discuss (and probably criticise each other) if no one take action.

**Comment by thenewvu** [comment]
@khanguy00 I agree with your points, except, that's not a random article, the article points to this thread, I also didn't criticize anyone, just saying that those lines in the quote don't help the situation better. I'm going to delete it now, I think the quote doesn't make the situation better either. And yes, this discussion makes no sense if no action was made. I'm done here.

**Comment by khanguy00** [comment]
@thenewvu thanks for not ignoring me. And sorry if I made you feel of my misunderstanding, but when I mentioned about "criticise", I just said in common sense. It's okay if we criticise each other in some points, I think.

**Comment by thaidn** [comment]
It looks like this has been fixed.

Since early May, Bluezone has started using rolling IDs, generated with an algorithm not unlike DP3T's.
