### ISSUE TITLE
Bluetooth UUID is hardcoded

### ISSUE THREAD

**Issue by sgn** [BluezoneGlobal/react-native-bluetooth-scan#7]
- https://github.com/BluezoneGlobal/react-native-bluetooth-scan/blob/d9ee70fd594093a30e50b6e62a7593a8397c2dab/lib/android/src/main/java/com/scan/AppConstants.java#L61
- https://github.com/BluezoneGlobal/react-native-bluetooth-scan/blob/d9ee70fd594093a30e50b6e62a7593a8397c2dab/lib/ios/Scanner/AppConstant.swift#L17
- https://github.com/BluezoneGlobal/react-native-bluetooth-scan/blob/d9ee70fd594093a30e50b6e62a7593a8397c2dab/lib/ios/Scanner/Contants.h#L15 this one isn't valid UUID

A quick search reveals: `08590F7E-DB05-467E-8757-72F6FAEB13D4` in https://stackoverflow.com/questions/23126501/what-the-custom-uuid-mean-for-ble-in-ios-sample:

> I can not find this UUID:@"08590F7E-DB05-467E-8757-72F6FAEB13D4" in Bluetooth Development Portal. Is that create by uuidgen in terminal ?

So, I guess those values shouldn't be hard coded, and maybe it's different in real system?

Sorry for my ignorance, I have total zero knowledge in mobile development.

**Comment by thuandt** [comment]
So far as I know, it also depend on CI/CD process to release the application. It can be change before build or release

**Comment by sgn** [comment]
Hi Thuan,

On 2020-04-28 20:37:56-0700, Thuan Duong <notifications@github.com> wrote:
> So far as I know, it also depend on CI/CD process to release the
> application. It can be change before build or release

I guess you're right.
But, I _think_ we need to cross-check with the apk uploaded to Google
Play.

But, there's an invalid UUID for bluetooth characteristic.
It isn't usable anyway.

-- 
Danh

**Comment by thanhnhan2tn** [comment]
Hi,
I  dont think it is using for CICD. It using here

https://github.com/BluezoneGlobal/react-native-bluetooth-scan/blob/d9ee70fd594093a30e50b6e62a7593a8397c2dab/lib/android/src/main/java/com/scan/AppUtils.java#L44

As far i know for peer-to-peer connection between Android devices such as smartphones u may use your own generated UUID. Devices must set same UUID to found each other and connect.
